-- This module is the root of the BombieriLangConjectureCanonicalLaneLean Lean proof package.
import BombieriLangConjectureCanonicalLaneLean.Basic
import BombieriLangConjectureCanonicalLaneLean.SourcePackage
import BombieriLangConjectureCanonicalLaneLean.SourceDependencies
import BombieriLangConjectureCanonicalLaneLean.Formalization
import BombieriLangConjectureCanonicalLaneLean.ReviewerBridge
import BombieriLangConjectureCanonicalLaneLean.TheoremStatement
import BombieriLangConjectureCanonicalLaneLean.MathlibObjects
import BombieriLangConjectureCanonicalLaneLean.AdmissibleClass
import BombieriLangConjectureCanonicalLaneLean.Projection
import BombieriLangConjectureCanonicalLaneLean.BridgeLemmas
import BombieriLangConjectureCanonicalLaneLean.GateLemmas
import BombieriLangConjectureCanonicalLaneLean.FinalTheorem
import BombieriLangConjectureCanonicalLaneLean.MathlibStatement
import BombieriLangConjectureCanonicalLaneLean.HeightGeneralTypeLayer
